disabled_rules:
- trailing_whitespace
- force_cast
- nesting
- identifier_name
- private_over_fileprivate
- multiple_closures_with_trailing_closure
- implicit_getter

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

type_name:
    min_length: 2
    max_length:
        warning: 60
        error: 80

variable_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

reporter: "xcode"
